import React from 'react';

const InsightExport = ({ insights }) => {
  const exportInsightsToPDF = async () => {
    if (insights.length === 0) return;

    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      // Add title
      doc.setFontSize(20);
      doc.text('Business Insights Report', 20, 20);
      
      // Add timestamp
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);
      
      // Add summary
      doc.setFontSize(12);
      doc.text(`Summary: ${insights.length} insights generated`, 20, 40);

      let yPosition = 55;

      // Group insights by impact
      const insightsByImpact = {
        High: insights.filter(i => i.impact === 'High'),
        Medium: insights.filter(i => i.impact === 'Medium'),
        Low: insights.filter(i => i.impact === 'Low')
      };

      // Add insights by impact level
      Object.entries(insightsByImpact).forEach(([impact, impactInsights]) => {
        if (impactInsights.length === 0) return;

        // Add new page if needed
        if (yPosition > 250) {
          doc.addPage();
          yPosition = 20;
        }

        // Impact level header
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text(`${impact} Impact Insights (${impactInsights.length})`, 20, yPosition);
        yPosition += 10;

        impactInsights.forEach((insight, index) => {
          // Add new page if needed
          if (yPosition > 240) {
            doc.addPage();
            yPosition = 20;
          }

          // Insight title
          doc.setFontSize(12);
          doc.setFont(undefined, 'bold');
          doc.text(`${index + 1}. ${insight.title}`, 25, yPosition);
          yPosition += 7;

          // Insight type and impact
          doc.setFontSize(10);
          doc.setFont(undefined, 'italic');
          doc.text(`Type: ${insight.type} | Impact: ${insight.impact}`, 25, yPosition);
          yPosition += 6;

          // Insight description
          doc.setFont(undefined, 'normal');
          const descLines = doc.splitTextToSize(insight.description, 165);
          doc.text(descLines, 25, yPosition);
          yPosition += descLines.length * 5 + 5;

          // Data summary
          if (insight.rowCount !== undefined) {
            doc.text(`Data Points: ${insight.rowCount}`, 25, yPosition);
            yPosition += 5;
          }

          // Sample data if available
          if (insight.data && insight.data.values && insight.data.values.length > 0) {
            doc.text('Sample Data:', 25, yPosition);
            yPosition += 5;

            // Headers
            doc.setFont(undefined, 'bold');
            const headerRow = insight.data.columns.slice(0, 3).join(' | ');
            doc.text(headerRow.substring(0, 60), 30, yPosition);
            yPosition += 5;

            // Sample rows
            doc.setFont(undefined, 'normal');
            const sampleRows = Math.min(2, insight.data.values.length);
            for (let j = 0; j < sampleRows; j++) {
              const dataRow = insight.data.values[j].slice(0, 3).map(v => 
                v === null ? 'NULL' : String(v).substring(0, 12)
              ).join(' | ');
              doc.text(dataRow.substring(0, 60), 30, yPosition);
              yPosition += 5;
            }
          }

          yPosition += 8; // Space between insights
        });

        yPosition += 5; // Space between impact levels
      });

      // Add footer
      doc.setFontSize(8);
      doc.text('Generated by AI BI Visualization Tool', 20, 280);

      // Save the PDF
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
      doc.save(`business_insights_${timestamp}.pdf`);
    } catch (error) {
      console.error('Error generating insights PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  return {
    exportInsightsToPDF
  };
};

export default InsightExport;