CREATE TABLE IF NOT EXISTS "Account" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Username"	TEXT,
	"Email"	TEXT,
	"FirstName"	TEXT,
	"LastName"	TEXT,
	"RoleType"	TEXT,
	"IsActive"	BOOLEAN,
	"CompanyId"	TEXT,
	"MobilePhone"	TEXT,
	"Address"	TEXT,
	"City"	TEXT,
	"State"	TEXT,
	"Zip"	TEXT,
	"SyncOnOpen"	BOOLEAN,
	"SyncOnClose"	BOOLEAN,
	"AppVersion"	TEXT,
	"Device"	TEXT,
	"PinColor"	TEXT,
	"PinStrokeColors"	TEXT,
	"CanManageRoutes"	BOOLEAN,
	"CanManageAdminPanel"	BOOLEAN,
	"CanManageSettings"	BOOLEAN,
	"PreventMoveRouteStops"	BOOLEAN,
	"PreventReorderRouteStops"	BOOLEAN,
	"Company"	JSON,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Chemical" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Description"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Company" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Name"	TEXT,
	"ActiveUntil"	DATETIME,
	"Accounts"	JSON,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "CompanyAddress" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Description"	TEXT,
	"Address"	TEXT,
	"City"	TEXT,
	"State"	TEXT,
	"Zip"	TEXT,
	"Latitude"	FLOAT,
	"Longitude"	FLOAT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "CompanySetting" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"MinutesAtStop"	INTEGER,
	"MinutesToLocation"	INTEGER,
	"MinutesPerMile"	FLOAT,
	"ShowTechCustomerPhone"	BOOLEAN,
	"ShowTechCustomerEmail"	BOOLEAN,
	"SortCustomersByFirstName"	BOOLEAN,
	"ServiceHistoryColumns"	TEXT,
	"CompanyId"	TEXT,
	"RequireSkippedStopReason"	BOOLEAN,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Customer" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"FirstName"	TEXT,
	"LastName"	TEXT,
	"CompanyName"	TEXT,
	"DisplayAsCompany"	BOOLEAN,
	"CustomerCode"	TEXT,
	"MobilePhone"	TEXT,
	"MobilePhone2"	TEXT,
	"MobileLabel1"	TEXT,
	"MobileLabel2"	TEXT,
	"HomePhone"	TEXT,
	"WorkPhone"	TEXT,
	"PrimaryEmail"	TEXT,
	"SecondaryEmail"	TEXT,
	"Email3"	TEXT,
	"Email4"	TEXT,
	"Notes"	TEXT,
	"BillingAddress"	TEXT,
	"BillingCity"	TEXT,
	"BillingState"	TEXT,
	"BillingZip"	TEXT,
	"QboCustomerId"	TEXT,
	"IsInactive"	BOOLEAN,
	"Tags"	JSON,
	"ServiceLocations"	JSON,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "CustomerTag" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"CustomerId"	TEXT,
	"TagId"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "EntryDescription" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Description"	TEXT,
	"UnitOfMeasure"	TEXT,
	"EntryType"	TEXT,
	"ReadingType"	TEXT,
	"DosageType"	TEXT,
	"SelectedIndex"	INTEGER,
	"Sequence"	INTEGER,
	"Cost"	FLOAT,
	"Price"	FLOAT,
	"CanIncludeWithService"	BOOLEAN,
	"ColumnSequence"	INTEGER,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "EntryValue" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"EntryDescriptionId"	TEXT,
	"Value"	FLOAT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "EquipmentItem" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"PoolId"	TEXT,
	"Description"	TEXT,
	"PartCategoryId"	TEXT,
	"PartMakeId"	TEXT,
	"PartModelId"	TEXT,
	"SoftDeleted"	BOOLEAN,
	"CompanyId"	TEXT,
	"Notes"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "InstalledItem" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"ServiceStopId"	TEXT,
	"Description"	TEXT,
	"EquipmentItemId"	TEXT,
	"ChemicalId"	TEXT,
	"ItemType"	TEXT,
	"PreviousStatus"	TEXT,
	"WorkOrderId"	TEXT,
	"ProductId"	TEXT,
	"Quantity"	FLOAT,
	"Price"	FLOAT,
	"DescriptionDisplay"	TEXT,
	"EquipmentDisplay"	TEXT,
	"DateDisplay"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Invoice" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"CustomerId"	TEXT,
	"InvoiceNumber"	INTEGER,
	"InvoiceDate"	DATETIME,
	"DueDate"	DATETIME,
	"Message"	TEXT,
	"Total"	REAL,
	"Subtotal"	REAL,
	"TaxAmount"	REAL,
	"AmountDue"	REAL,
	"Status"	TEXT,
	"PaymentStatus"	TEXT,
	"PaidAmount"	REAL,
	"CanAutopay"	INTEGER,
	"VoidReason"	TEXT,
	"FeeName"	TEXT,
	"DiscountName"	TEXT,
	"FeeFlat"	REAL,
	"FeePercent"	REAL,
	"FeeTotal"	REAL,
	"DiscountTotal"	REAL,
	"DiscountFlat"	REAL,
	"DiscountPercent"	REAL,
	"QuoteId"	TEXT,
	"AutopayMethodExists"	INTEGER,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "InvoiceItem" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"InvoiceLocationId"	TEXT,
	"Sequence"	INTEGER,
	"Item"	TEXT,
	"Description"	TEXT,
	"Quantity"	REAL,
	"Rate"	REAL,
	"CostQuantity"	REAL,
	"Cost"	REAL,
	"IsTaxable"	BOOLEAN,
	"RouteStopId"	TEXT,
	"WorkOrderId"	TEXT,
	"InstalledItemId"	TEXT,
	"EntryDescriptionId"	TEXT,
	"Source"	INTEGER,
	"ServiceDates"	TEXT,
	"FeeTotal"	REAL,
	"DiscountTotal"	REAL,
	"Amount"	REAL,
	"Subtotal"	REAL,
	"ProductId"	TEXT,
	"WorkOrderTypeId"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "InvoiceLocation" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"ServiceLocationId"	TEXT,
	"InvoiceId"	TEXT,
	"TaxGroupId"	TEXT,
	"FeeFlat"	REAL,
	"FeePercent"	REAL,
	"DiscountFlat"	REAL,
	"DiscountPercent"	REAL,
	"RateType"	INTEGER,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "LocationWorkOrderType" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"ServiceLocationId"	TEXT,
	"WorkOrderTypeId"	TEXT,
	"LastDoneDate"	DATETIME,
	"PreviousLastDoneDate"	DATETIME,
	"LaborCost"	FLOAT,
	"Price"	FLOAT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "PartCategory" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Description"	TEXT,
	"ItemDescription"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "PartMake" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"PartCategoryId"	TEXT,
	"Description"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "PartModel" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"PartMakeId"	TEXT,
	"Description"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Payment" (
	"CreatedAt"	DATETIME,
	"UpdatedAt"	DATETIME,
	"Deleted"	BOOLEAN,
	"Version"	BLOB,
	"id"	TEXT,
	"CustomerId"	TEXT,
	"InvoiceId"	TEXT,
	"LastFailedDate"	DATETIME,
	"PaymentDate"	DATETIME,
	"PaymentOrigin"	TEXT,
	"PaymentType"	TEXT,
	"PaymentMethod"	TEXT,
	"Status"	TEXT,
	"StatusMessage"	TEXT,
	"Reference"	TEXT,
	"Currency"	TEXT,
	"Amount"	REAL,
	"PaymentIntentId"	TEXT,
	"PaymentIntentStatus"	TEXT,
	"PaymentFeeId"	TEXT,
	"ApplicationFee"	REAL,
	"AmountRefundedOnline"	REAL,
	"AmountRefundedOffline"	REAL,
	"ErrorCode"	TEXT,
	"DeclineCode"	TEXT,
	"PayoutId"	TEXT,
	"IsCustomerInitiated"	BOOLEAN,
	"PaymentMethodId"	TEXT,
	"SourcePaymentMethod"	TEXT,
	"IsAutopay"	BOOLEAN,
	"VoidReason"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Pool" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"ServiceLocationId"	TEXT,
	"Name"	TEXT,
	"Gallons"	INTEGER,
	"BaselineFilterPressure"	FLOAT,
	"Notes"	TEXT,
	"EquipmentItems"	JSON,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Product" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Name"	TEXT,
	"DefaultDescription"	TEXT,
	"ProductCategoryId"	TEXT,
	"DefaultPrice"	FLOAT,
	"IsTaxable"	BOOLEAN,
	"QboItemId"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "ProductCategory" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Description"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "RouteAssignment" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"ServiceLocationId"	TEXT,
	"AccountId"	TEXT,
	"DayOfWeek"	TEXT,
	"Frequency"	TEXT,
	"StartDate"	DATETIME,
	"EndDate"	DATETIME,
	"Sequence"	INTEGER,
	"CompanyId"	TEXT,
	"Status"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "RouteMove" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"RouteAssignmentId"	TEXT,
	"ServiceLocationId"	TEXT,
	"OriginalAccountId"	TEXT,
	"OriginalServiceDate"	DATETIME,
	"MoveToAccountId"	TEXT,
	"MoveToServiceDate"	DATETIME,
	"CreatedDate"	DATETIME,
	"Sequence"	INTEGER,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "RouteSkip" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"RouteAssignmentId"	TEXT,
	"ServiceDate"	DATETIME,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "RouteStop" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"AccountId"	TEXT,
	"ServiceLocationId"	TEXT,
	"RouteAssignmentId"	TEXT,
	"ServiceDate"	DATETIME,
	"StartTime"	DATETIME,
	"CompleteTime"	DATETIME,
	"IsSkipped"	BOOLEAN,
	"SkippedStopReasonId"	TEXT,
	"IsOffBiweekly"	BOOLEAN,
	"Sequence"	INTEGER,
	"MinutesAtStop"	INTEGER,
	"RouteMoveId"	TEXT,
	"EmailHeader"	TEXT,
	"EmailMessage"	TEXT,
	"PhotoUrl"	TEXT,
	"EmailStatus"	TEXT,
	"EmailSentDate"	DATETIME,
	"CompanyId"	TEXT,
	"ServiceStops"	JSON,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "ServiceLocation" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"CustomerId"	TEXT,
	"Address"	TEXT,
	"City"	TEXT,
	"State"	TEXT,
	"Zip"	TEXT,
	"LocationCode"	TEXT,
	"Latitude"	FLOAT,
	"Longitude"	FLOAT,
	"MinutesAtStop"	INTEGER,
	"IsBadAddress"	BOOLEAN,
	"GateCode"	TEXT,
	"DogsName"	TEXT,
	"Notes"	TEXT,
	"Rate"	FLOAT,
	"RateType"	TEXT,
	"LaborCost"	FLOAT,
	"LaborCostType"	TEXT,
	"Pools"	JSON,
	"RouteAssignments"	JSON,
	"RouteMoves"	JSON,
	"WorkOrderModels"	JSON,
	"RecurringWorkItems"	JSON,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "ServiceStop" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"RouteStopId"	TEXT,
	"PoolId"	TEXT,
	"PoolName"	TEXT,
	"ServiceDate"	DATETIME,
	"Notes"	TEXT,
	"NotesToCustomer"	TEXT,
	"NoteIsAlert"	BOOLEAN,
	"NoteIsHandled"	BOOLEAN,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "ServiceStopCalculatorEntry" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"ServiceStopId"	TEXT,
	"WorkOrderId"	TEXT,
	"PoolId"	TEXT,
	"EntryType"	TEXT,
	"Value"	FLOAT,
	"CompanyId"	TEXT,
	"ServiceDate"	DATETIME,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "ServiceStopEntry" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"ServiceStopId"	TEXT,
	"PoolId"	TEXT,
	"EntryDescriptionId"	TEXT,
	"EntryType"	TEXT,
	"Value"	FLOAT,
	"ServiceDate"	DATETIME,
	"CompanyId"	TEXT,
	"EntryDescriptionText"	TEXT,
	"UnitOfMeasure"	TEXT,
	"ReadingType"	TEXT,
	"SelectedIndex"	INTEGER,
	"Sequence"	INTEGER,
	"ValueDisplay"	TEXT,
	"WorkOrderId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "ShoppingListItem" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Description"	TEXT,
	"DescriptionDisplay"	TEXT,
	"PoolId"	TEXT,
	"EquipmentItemId"	TEXT,
	"PartCategoryId"	TEXT,
	"PartMakeId"	TEXT,
	"PartModelId"	TEXT,
	"ChemicalId"	TEXT,
	"ProductId"	TEXT,
	"Quantity"	FLOAT,
	"Price"	FLOAT,
	"CustomerName"	TEXT,
	"AddedBy"	TEXT,
	"ProductName"	TEXT,
	"Equipment"	TEXT,
	"Chemical"	TEXT,
	"ItemStatusDescription"	TEXT,
	"ItemType"	TEXT,
	"ItemStatus"	TEXT,
	"WorkOrderId"	TEXT,
	"InstalledItemId"	TEXT,
	"AddedByAccountId"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "SkippedStopReason" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"CompanyId"	TEXT,
	"Reason"	TEXT,
	"Sequence"	INTEGER,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Tag" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Name"	TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "TaxGroup" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Name"	TEXT,
	"IsActive"	BOOLEAN,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "TaxGroupRate" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"TaxRateId"	TEXT,
	"TaxGroupId" TEXT,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "TaxRate" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Name"	TEXT,
	"Rate"	FLOAT,
	"IsActive"	BOOLEAN,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "WorkOrder" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"WorkOrderTypeId"	TEXT,
	"ServiceLocationId"	TEXT,
	"WorkNeeded"	TEXT,
	"WorkPerformed"	TEXT,
	"AddedByAccountId"	TEXT,
	"AddedOnDate"	DATETIME,
	"AccountId"	TEXT,
	"ServiceDate"	DATETIME,
	"ScheduledTime"	TEXT,
	"StartTime"	DATETIME,
	"CompleteTime"	DATETIME,
	"RouteSequence"	INTEGER,
	"EstimatedMinutes"	INTEGER,
	"LaborCost"	FLOAT,
	"Price"	FLOAT,
	"IsInvoiced"	BOOLEAN,
	"SyncDate"	DATETIME,
	"EmailHeader"	TEXT,
	"EmailMessage"	TEXT,
	"EmailStatus"	TEXT,
	"EmailSentDate"	DATETIME,
	"CompanyId"	TEXT,
	"Notes"	TEXT,
	"NoteIsAlert"	BOOLEAN,
	"NoteIsHandled"	BOOLEAN,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "WorkOrderType" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"Description"	TEXT,
	"ColorCode"	TEXT,
	"RecurMonths"	INTEGER,
	"DefaultWorkNeeded"	TEXT,
	"DefaultWorkPerformed"	TEXT,
	"DefaultMinutes"	INTEGER,
	"DefaultLaborCost"	FLOAT,
	"DefaultPrice"	FLOAT,
	"AllowTechsToAdd"	BOOLEAN,
	"NeedsToBeInvoiced"	BOOLEAN,
	"SendAlert"	BOOLEAN,
	"PhotoIsRequired"	BOOLEAN,
	"SendEmail"	BOOLEAN,
	"DefaultEmailSubject"	TEXT,
	"DefaultEmailHeader"	TEXT,
	"DefaultEmailMessage"	TEXT,
	"SoftDeleted"	BOOLEAN,
	"Sequence"	INTEGER,
	"CompanyId"	TEXT,
	"Recurs"	BOOLEAN,
	"RecurType"	TEXT,
	"RecurValue"	INTEGER,
	"SendFinishedAlert"	BOOLEAN,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "WorkOrderTypeShoppingListItem" (
    "CreatedAt" DATETIME,
	"UpdatedAt" DATETIME,
	"Deleted" BOOLEAN,
	"Version" BLOB,
	"id"	TEXT,
	"WorkOrderTypeId"	TEXT,
	"Description"	TEXT,
	"ChemicalId"	TEXT,
	"ItemType"	TEXT,
	"ProductId"	TEXT,
	"Quantity"	REAL,
	"Price"	NUMERIC,
	"CompanyId"	TEXT,
	PRIMARY KEY("id")
);
